INSERT INTO users (name, age) VALUES ("Kevin", 37);
INSERT INTO users (name, age) VALUES ("Shane", 23);
INSERT INTO users (name, age) VALUES ("Ashley", 29);
INSERT INTO users (name, age) VALUES ("Bennet", 21);
INSERT INTO users (name, age) VALUES ("Devin", 22);
INSERT INTO users (name, age) VALUES ("Dalton", 27);
INSERT INTO users (name, age) VALUES ("Ryan", 30);
INSERT INTO users (name, age) VALUES ("Ellen", 29);
INSERT INTO users (name, age) VALUES ("Vicky", 28);
INSERT INTO users (name, age) VALUES ("Imran", 20);
INSERT INTO users (name, age) VALUES ("Luke", 28);
INSERT INTO users (name, age) VALUES ("Hilary", 32);
INSERT INTO users (name, age) VALUES ("Donald", 72);
INSERT INTO users (name, age) VALUES ("Chris", 25);
INSERT INTO users (name, age) VALUES ("Ivie", 20);
INSERT INTO users (name, age) VALUES ("Lillie", 19);
INSERT INTO users (name, age) VALUES ("John", 27);
INSERT INTO users (name, age) VALUES ("Paul", 30);
INSERT INTO users (name, age) VALUES ("David", 12);
INSERT INTO users (name, age) VALUES ("Cornelius", 88);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pants", "News", 300, "03/20/2009", "09/13/2009");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Banana", "Commerce", 500, "07/01/2002", "05/17/2005");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Elf", "Commerce", 500, "07/01/2002", "05/17/2005");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Microsoft", "Computer", 2000000, "01/01/2020", "05/23/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sony", "Gaming", 50000, "07/19/2006", "11/17/2006");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Nintendo", "Gaming", 30000, "02/01/1986", "11/19/2006");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Kickstarter", "Fundraiser", 100000, "02/06/2012", "08/17/2012");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("SQL", "Coding Language", 7, "11/01/1973", "2/03/1991");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Toys 'r' Us", "Chain Store", 22000, "12/12/1990", "08/17/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Target", "Chain Store", 13000, "02/01/1995", "10/10/1997");

INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3, 10, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 8, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (94, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (77, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (95, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (943, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (33, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (99, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 18, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (31, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (44, 14, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (62, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (101, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (430, 19, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (22, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (104, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (88, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 7, 5);